### ISSUE TITLE
Metroid Prime Trilogy doesn't load after selecting game

### ISSUE THREAD

**Issue by yannick1124** [shiiion/dolphin#105]
I am trying to play Metroid Prime: Trilogy, which I downloaded through Wii U USB Helper.

Whenever I select Metroid Prime or any of the other games (within Metroid Prime Trilogy) the game just freezes on "Metroid Prime loading..."

I don't really know if this is an issue with Dolphin or a PrimeHack issue but regardless, this seemed like the best place to ask this question.

**Comment by vyuuui** [comment]
Please don’t admit to pirating your copy of the game. We really don’t care how you got it, just please don’t tell us, otherwise it puts us in a weird spot. 
Re-dump a legally acquired version, or get it directly from the wii-u shop without using a legally questionable tool. You can also play the original GameCube games with primehack, as people are more likely to have a legally acquired copy of those.
Aside from the above, we cannot offer any more assistance.
