### ISSUE TITLE
Changing the FOV creates culling issues in MP2 multiplayer

### ISSUE THREAD

**Issue by ProfessionalismIsMyMiddleName** [shiiion/dolphin#113]
Only tested in trilogy in two player mode.

Any FOV above 67 creates big culling issues.

I think the screen being divided (or maybe the black bars on the side in 16/9?) creates errors in the FOV calculations, and makes it effectively bigger than the chosen value. At least, the effective FOV looks much higher than 67. Coincidentally, 67 is 2/3 of 101, the max FOV value without issues in  MP2. Maybe the fix would be as simple as multiplying FOV by 2/3 in multiplayer, maybe some more adjustments would be needed for 3 or 4 players, I don't know.

Btw, disabling culling obviously fixes the issue, but I'd like to avoid that if I can, plus having the same effective FOV in solo and mp without having to change the setting is better UX, am I right?

**Comment by SirMangler** [comment]
Multiplayer isn't officially supported since PrimeHack was designed to only interact with Player 1 and assumes all inputs effect them (so you can get some pretty wacky behaviour). 

But this is good to know if we ever look into supporting it for the sake of Parsec or Local co-op. Note, netplay is entirely broken with PrimeHack and neither me or shio are willing to go into that 13 year-old code to fix it / support everything.

Honestly I didn't even know if the other player's FoV would be modified.

**Comment by ProfessionalismIsMyMiddleName** [comment]
I see, I wasn't aware MP was unsupported.

What netplay are you talking about? Is there any online fonctionnality in the prime series besides the friend ticket exchange in 3/trilogy?

**Comment by SirMangler** [comment]
> I see, I wasn't aware MP was unsupported.

You'll note that player 2's controls outright do not work with primehack controls.


> What netplay are you talking about? Is there any online fonctionnality in the prime series besides the friend ticket exchange in 3/trilogy?


Netplay is a built in online multiplayer system that was added to Dolphin a long time ago, it was designed to let people play local co-op games online, but its very old and sensitive to any form of desyncs or non-deterministic behaviour.
