### ISSUE TITLE
[Question] best method/saves to test/verify settings? any version differences? why is the audio causing slowdowns on a beast PC?

### ISSUE THREAD

**Issue by braezer** [shiiion/dolphin#129]
been testing and tweaking my settings for a while now but to be 100% sure they're dialed in right, I need to know if the intro for the game is enough to see if they're perfect (my idea is that it was trailer and demo showcasing the GC's full power)? if not, are any saves available to quickly load and check for slowdowns/desync/etc.? also, which version of the game(s) has the best compatibility? e.g. for MP1, DOL-GM8E-0-02 vs DOL-GM8E-0-01 vs PAL vs Trilogy, because the compatibility chart only says "supported" and I'd rather not use Trilogy unless necessary due to the reduced texture quality (and afaik the invisible walls from the 1.2 patch)?

-I found out the hard way that rebooting is necessary between changing certain settings, e.g. I swapped from none to 16x MSAA and the graphics died on walking through the first door. lol (also noticed my VRAM wasn't clearing itself; bug reported separately)

-During the theme tune before the load file screen, as well as during the intro cutscene, and somewhere after the parasite queen during gameplay there was an audio hitch: I seem to have fixed this by disabling Dual Core and enabling the time stretching audio buffer setting, but unable to verify until I come to later areas of the game with more intense sound mixing.

-I tried DSP LLE Interpreter on Cubeb but this caused insane frame drops on killing the diseased pirates so I had to swap back to HLE, however I have no idea why because my CPU is barely being touched? (I have an ASIO mixer that goes from 44.1kHz to 192kHz sample rate with a bit-depth of 24 to test if it's the sample rate being re-muxed, but ASIO isn't a selectable backend option, and idk if the game's audio is even 44.1kHz anyway) either way this and the above audio issue suggests to me that most of the de-sync/stuttering/etc. is due to the audio and NOT the graphics

for reference I'm using GM8E-01 and DirectX 12, windows 10 LTSC IoT, a golden sample 5800x3D (4.37GHz all core when benched, -30 on PBO2 with no issues) and an MSI suprim x 3090 (which seems to be operating at a gpu clock of 480MHz and memory clock of 101MHz most of the time so maybe some of the issues is from power save states swapping, since using 16x MSAA caused slowdowns at killing the parasite queen where they ramped up to 1875 and 1219 respectively for like, one frame entering PCIe 3.0 mode power state instead of PCIe 2.0 which it had been until then according to GPU-z)

**Comment by braezer** [comment]
well apparently the beginning sequence was enough for me, as I got it entirely stable and playable from just going through the intro to the escape multiple times.

main points to notice that I can remember:
hitching when the camera is panning along the station during the intro cutscene (before samus exists the vehicle) - solved with  audio stretch enabled
hitching when killing the pirate - solved with using DSP HLE and audio stretching
hitching during the Parasite Queen death cutscene - solved with audio again, and reducing Anti-Aliasing so it doesn't create a massive power/performance spike to my GPU

also I just noticed I don't have the option for 16x MSAA anymore, only 8x, but meh, 2x was perfectly fine anyway
I was able to re-enable dual-core after increasing my time stretching on the audio to 160ms
still had a couple slowdowns, but these were due to opening the map whilst effects were on screen (e.g. shoot a wall with the ice beam and open map) or when I first shot the charged ice beam on a baby sheegoth destroying its bum crystal (first-time loading thing I guess cause it never happened after that one time)

**Comment by vyuuui** [comment]
Most of these questions are not relevant to Primehack, as we're not advertising "game optimization", just alternative control scheme and a few other QoL features. I'll respond to a few questions here, though.

- Any area which has a lot of active things that are all being rendered is a good test for performance hitches. Disabling culling will also force everything to be rendered, so it will tank framerate in large rooms (e.g. Chozo Plaza).
- Why different audio emulation causes slowdowns? That's not for me to answer, you're better off asking someone who worked on that. Besides that, audio stretching is a hack solution to avoid crackling due to framedrops, as you're now getting an alternative uncanny effect of sound being delayed.
- Dual core should be *speeding up* emulation, not slowing it down. With dual core on, you sacrifice stability for better performance.

Once again, please report these issues to Dolphin, we are neither capable nor qualified to deal with these performance problems in a manner besides changing what the game does itself.
