### ISSUE TITLE
Port to Android?

### ISSUE THREAD

**Issue by Destroyer5150** [shiiion/dolphin#13]
This https://apkpure.ai/diii4a-source-port-of-doom-3 can be used for mouse and keyboard touch controls

**Comment by SirMangler** [comment]
Theoretically PrimeHack could work on Android if you compiled it yourself and used an XInput or DInput device with it (aka most peripheral devices). While it wouldn't natively support touchscreen input, using **Controller Mode** you could control the camera. 

You will probably need to modify the config files to change PrimeHack settings since I haven't made any UI for Android, but Qt is designed for multi-platforming so it is possible.

I haven't tested this and can't, I do not own an Android device.
