### ISSUE TITLE
Grapple Lasso does not pull back if multiple functions assigned to the same button in MP3

### ISSUE THREAD

**Issue by up2urheadlights** [shiiion/dolphin#139]
I wanted to mimic the controls of the newly released MP Remaster, and so I am using a Pro Controller and BetterJoy.  I have both Grapple Lasso and Lock-On mapped to the left trigger, to most correctly map the controls of the Remaster.  This results in the successful lock on, and the grapple lasso fires and you see the lightning effects, however, the part that pulls the emulated wii mote backwards to rip the lock off doors does not work.  I can confirm that if Lock-On and Grapple Lasso are assigned to different buttons, then the pull back is executed and the doors are able to be unlocked.

**Comment by SirMangler** [comment]
By design of the game, lock-on and grapple lasso are two separate actions. You need to lock-on before you can initiate a grapple, and releasing lock-on will release your grapple target. If you bind those two controls together, releasing the grapple lasso bind (as you need to) will also release lock-on, subsequently cancel grapple lasso (or at least, it should). I'm not sure how we would 'fix' this to be honest, should we redesign it to maintain the grapple lock after letting go of 'lock-on', you would be softlocked on grapple targets which don't automatically cancel for you, unless we discovered a way to identity every grapple target that doesn't release grapple automatically.

More importantly, there are scenarios in the game where you don't want to automatically grapple (eg shield pirates), by forcing the two actions to perform simultaneously you'll end up with unintuitive controls, such as lock-on working 'fine' until you get too close to the target. This is likely why Retro designed it like this, rather than having it be automatic like grapple hook is. 

So, while we could look into altering this behaviour to allow this control scheme, it's not necessarily a control scheme I would want to encourage, despite how it may initially appear to be fine with the first grapple lasso door.

**Comment by up2urheadlights** [comment]
I understand the reluctance to implement this based on all the reasons you have explained.  It will be interesting to see how the developer will implement the controls if and when MP3 is released on Switch.  For now I have mapped grapple lasso to a different input and kept lock on mapped to the left trigger.
