### ISSUE TITLE
Is it possible to not snap the view back after locking on?

### ISSUE THREAD

**Issue by Unreal-Dan** [shiiion/dolphin#28]
When you lock onto something naturally your view snaps to the target, but when you let go of the lock your view snaps back to where it was before.  

Is it possible, or planned, to have the view remain where you snapped to after letting go of the lock-on button?  

By the way, beautiful hack here I absolutely love it. 

I'd love to make this change happen (if it's desired) but I might need a few nudges in the right direction, I'm strong with C/C++/x86 but not so much powerPC. Also never written any code for dolphin or any emulators for that matter.

**Comment by SirMangler** [comment]
This is because when you lock-on, PrimeHack temporarily stops writing to the pitch and yaw values in order to allow the game to take control and lock the camera in orbit to what you're locking onto. However when you let go of lock-on, it starts writing the data of *where it thinks you're aiming* without knowing the camera has since moved. It also continues to take input data as if you can still aim. This issue manifests in various locations of similar scenarios.

I would really like this to be fixed and I intend on spending some time to solve it. 

I believe you could make this change fairly simply without requiring any assembly knowledge. Essentially we need PrimeHack's side to update to the new position (or compensate for it), or reset the input values from the mouse/gamepad to zero if possible. The latter solution I believe could work because upon starting the game for the first time, the camera is not placed into a seemingly random location.

Everything required should be in PrimeHack already and reasonably self-explanatory, although you may need to take a look at the input APIs, XInput2 and DInput (see `InputCommon/XInput2Mouse.cpp` and `InputCommon/DInputMouseAbsolute.cpp`).

**Comment by shiiion** [comment]
This should be fixed with 24b8a5f8e5f55c19cdef804290d37aafe3142b40
