### ISSUE TITLE
Arm cannon vanishes instantly when scan visor is engaged.

### ISSUE THREAD

**Issue by Celandine** [shiiion/dolphin#51]
When the player activates the scan visor, Samus' arm cannon disappears instantly. Footage from real Wii consoles shows that there is supposed to be an animation of her lowering her arm out of view. 
I've so far only tested this on the PAL version of Prime Trilogy for the Wii, and so far only in Metroid Prime 2.
Possibly related to the viewmodel offset feature?

**Comment by SirMangler** [comment]
This is because of the way we trigger beam and visor swaps with our code changes to load a flag from PrimeHack and trigger the swap. As the name of the project suggests, this is a hack and doesn't perform the same code for native beam/visor swapping.

We could trigger the animation to lower the cannon, there's a state in the CPlayer class which can be set to trigger the "holstering". The trouble is we support so many games that any task now is pretty big to ensure that all the games are working between the version differences.

**Comment by Celandine** [comment]
Yeah, I realised today that it animates properly if I use the visor menu, it's only a problem with the hotkey swap.

**Comment by SirMangler** [comment]
Resolved in: https://github.com/shiiion/dolphin/commit/3f1d848d844ae775652ab769ab6a5f6f34e5dcc4
