### ISSUE TITLE
[Request] Trilogy Hypermode Difficulties Unlocked From the Start

### ISSUE THREAD

**Issue by doodleintime** [shiiion/dolphin#71]
One of the extra features of MPT was new Hypermode difficulties for all 3 of the Prime games, as an extra challenge for people good at the Prime games, which is cool. The problem lies with how you normally unlock them. If you want to play the Hypermode difficulty for a game, you have to beat it, and then you can select the save that you beat the game on and start a new game in Hypermode. 

You don't even unlock the difficulty permanently for that game, as if you want to start over by deleting a save file for that game, Hypermode becomes locked again. This is why always having Hypermode difficulty unlocked, or a least a code for it, would be convenient.

**Comment by SuperSamus** [comment]
This can be closed since it's been fixed by feeee358e94028a7ad9affb69ffb201cd4ac63e5.

**Comment by SuperSamus** [comment]
Now that I think about it, the code is only for Prime Trilogy, right? If that's the case, the descriptions don't specify it, and they probably should since a user might assume that the cheat might work in all games (it's named "Hard" instead of "Hypermode" in MP1 and MP2 standalone, but the point stands).
