### ISSUE TITLE
Camera mode and controller profiles (Wii)

### ISSUE THREAD

**Issue by Formedras** [shiiion/dolphin#77]
When loading Wii control profiles, PrimeHack does not maintain the profile's choice of `Mouse` or `Controller` camera settings. This is specific to Wii controls; GameCube profiles load this choice correctly.

EDIT: I looked at the controller profiles in VS Code; when camera mode is set to `Mouse`, the saved profile doesn't even have a line referring to it. Only if it's set to `Controller`. This is still true if the profile is saved with it set to `Controller`, then changed to `Mouse` and resaved. The line is removed in this case.
I don't know if this is relevant, but it's something to note.

**Comment by SirMangler** [comment]
>  when camera mode is set to Mouse, the saved profile doesn't even have a line referring to it.

This is how Dolphin saves settings. Mouse mode is the default option. Dolphin does not save default settings as it is technically not necessary, since if the setting isn't found in the config, the default value is loaded instead.

Good catch on this, it is now resolved in this commit: https://github.com/shiiion/dolphin/commit/b76a85d6aab140d2165e3d3ffbc563bc89f11c10
