### ISSUE TITLE
Beam/visor bindings missing if you run Dolphin then PrimeHack

### ISSUE THREAD

**Issue by nyanpasu64** [shiiion/dolphin#8]
- Create a profile in stock Dolphin. This creates a folder "%userprofile%\Documents\Dolphin Emulator\".
- Open the profile in PrimeHack.

The keybinds to switch beams/visors are missing.

**Comment by nyanpasu64** [comment]
https://github.com/shiiion/dolphin/wiki/Installation#primehack-defaults-important

https://camo.githubusercontent.com/c6930b537cddf3cc8dfd2a087219d8f762c05fae/68747470733a2f2f692e696d6775722e636f6d2f615068355878732e706e67

Didn't realize it's documented already. I don't know what's the optimal solution. Should PrimeHack be bundled with `portable.txt` by default?

**Comment by SirMangler** [comment]
PrimeHack already delivers a working *default* profile designed to work with PrimeHack in Prime Trilogy. However if you launch regular Dolphin before PrimeHack, its defaults will be loaded and PrimeHack does not see the difference between Dolphin defaults and a control profile the user has have designed. 

This problem is not exclusive to PrimeHack and is more related to Dolphin itself.
For most games a given controller profile is good for one game but unideal for another game, this is especially the case with Prime Trilogy. The only way to deliver per-game control profiles is by using the `Save`/`Load` profile feature. 

You can choose to use portable mode to make a per-installation config and there was a time we did enforce this, but we realised this was a poor decision, since this is not ideal for every user, and many users (such as myself) would like to share the settings with regular dolphin.

The reason PrimeHack has done nothing about this problem is that it would be unfair and frustrating to a user to **force** our profile onto them, potentially leading them to lose their existing profile. I would like to investigate more options and I have came up with some ideas that should hopefully *reduce* this issue with users.

If you have further questions I recommend you see our Discord.

https://discord.gg/hYp5Naz
