### ISSUE TITLE
Pixel bug in Prime 1

### ISSUE THREAD

**Issue by AnonWolf6** [shiiion/dolphin#86]
Hi, I read on the website and patch notes for the latest version that the “pixel fix for real this time” was applied, but I’m currently seeing a black (during gameplay and cutscenes)/white (during the dialogs for acquiring new items) mark right in the middle of the screen. Is that what the supposed fix is talking about? It’s not game breaking just annoying especially with all the cutscenes in Prime 1. 

Edit: seems this also happens in Prime 2 and I'm assuming Prime 3. Might also be linked to running at higher than 1x internal resolution?

**Comment by SirMangler** [comment]
It is an artefact due to upscaling the resolution, and our fix only focuses on removing it when in first person in gameplay, not cutscenes or menus due to them being caused by a different and currently unidentified texture.

We cannot fix this unless those textures are identified. Please also note our fix can and will be overridden by custom textures. This is only a problem if you're using an upscaled texture pack which bulk upscaled every single dumped texture without thought, which would include the broken texture (usually AI upscales do this).

**Comment by AnonWolf6** [comment]
Thank you for your insight. Do you know of an HD texture pack that doesn’t conflict with your fix? I understand if not.

**Comment by SirMangler** [comment]
> Thank you for your insight. Do you know of an HD texture pack that doesn’t conflict with your fix? I understand if not.

Sorry, no. The HD HUD UI pack should be okay, anything made by hand.
