### ISSUE TITLE
Scrolling to switch visors (beams) doesn't work

### ISSUE THREAD

**Issue by nyanpasu64** [shiiion/dolphin#9]
- default bindings for switching beams/visors is LSHIFT & Axis Z+ (mouse scroll). This is invalid with error "Expected end of expression." You need backticks like \`Axis Z+\`
- Both next and previous beam is bound to Z+. One should be Z-.
- Even after I fix this, shift+scrolling to switch visors still doesn't work in Metroid Prime 2. I haven't gotten to beams yet.

**Comment by SirMangler** [comment]
The issue arose from when visor scrolling was implemented. The quotes weren't required for the simple expression with only one bind, but when `SHIFT` was added to the expression it became an issue. Good catch. Thank you!

The problem with scrolling in Prime 2 has been resolved and will be fixed in the next release.

https://github.com/shiiion/dolphin/commit/66c3143e217fa7990fa4e59178ecb7b7e4da4ce4
