### ISSUE TITLE
Request: Add optional turbo fire  as a configurable button

### ISSUE THREAD

**Issue by jvook** [shiiion/dolphin#90]
Adding a rapid fire mapping for Shoot/Select, separately configurable from the charge shot, will help with repetitive stress

**Comment by SirMangler** [comment]
This already exists in vanilla Dolphin. You can do this as well as many other complex configurations with their `Advanced Configure Input` window which is opened by right clicking the bind. 

Here is an example of an expression for rapid fire under Left Click **and** a separate button (Right Click) you can hold for charge beam.

![image](https://user-images.githubusercontent.com/4237834/150650754-16c523d3-f0f4-41c9-9329-4a078da05882.png)


For more information or help on making these binds, you can join our Discord or seek help within the Dolphin community, seeing as this is their feature rather than ours.

**Comment by jvook** [comment]
How about the 3-round burst and charge from metroid prime hunters?
