### ISSUE TITLE
Music randomly doesn't start when transitioning to different song

### ISSUE THREAD

**Issue by Kwonunn** [shiiion/dolphin#98]
Since I've updated to 1.0.5 there has been this strange bug. Sometimes when the music changes because you go to a new room the old music will fade out, but the new track won't start. This seems to happen most commonly with elevator rooms and save rooms, both when entering them and when leaving them.

It usually fixes itself when you go through another music transition, including the one that just didn't work.

I'm quite sure this wasn't a problem before 1.0.4, because I never noticed it and now I notice every time.

I'm playing on Metroid Prime Trilogy R3ME01. It only seems to happen in Prime 1, as I haven't been able to reproduce it in about an hour of testing in Prime 2. I haven't tried 3, but I'll update the issue later if I do.

**Comment by Kwonunn** [comment]
I've just done some more testing on a fresh 1.0.5 install with no settings changed except the controls. The bug still only seems to occur in Prime 1.

**Comment by SirMangler** [comment]
> I've just done some more testing on a fresh 1.0.5 install with no settings changed except the controls. The bug still only seems to occur in Prime 1.

This problem has existed for a very long time, it's caused by `Speed Up Disk Transfer` (found in the game properties) making the game load faster than anticipated. PrimeHack it self has no interaction with how rooms, assets or entities (including trigger boxes and music queues) are loaded, or how the disc is read. 

The only relevant difference I can think of between 1.0.4 and 1.0.5 is the fact PrimeHack is on a later version of Dolphin, by a few beta releases. It is also worth mentioning, it is very likely it was a simple coincidence you did not get this issue commonly on 1.0.4, seeing as not everyone gets it to begin with.

Nearly every primehack feature can be disabled, if you find this problem disappears after disabling one of them, please re-open this. Otherwise, I'm 99% sure this is just a quirk with Dolphin and speed up disc transfer, not us.
