### ISSUE TITLE
Generic controller drifting to the lower right side on camera controls on Linux (Flatpak)

### ISSUE THREAD

**Issue by djkido316** [shiiion/dolphin#99]
PrimeHack/Dolphin: Release 1.0.5 using Flatpak
ROMS:, Metroid Prime 1&2 (GC) and Metroid Prime 3 (WII) - USA ROMS
OS: Zorin OS 16.1 also tried on Ubuntu 21.10 and Manjaro 21.2.4

Issue : Tried with several generic controllers, When the camera control is bound to right analog stick it drifts to the lower right side although it stops when you start moving, Only happens in Linux, Windows 10 x64 version of primehack works flawlessly.

GIF of the issue posted below.

![](https://media.giphy.com/media/MGxciNxhTOnMroGtBh/giphy-downsized-large.gif)

Thank you!

**Comment by SirMangler** [comment]
I can't tell you why this is more noticeable on Linux as opposed to Windows, unless you just got lucky on Windows and you have slightly sticky sticks, but this problem is generally due to the fact PrimeHack doesn't handle a significant deadzone by default. 

You can set one yourself under the controller bindings. Generally smaller is better to have the largest range of input. Drift is very common for controllers and deadzone tends to be done behind the scenes on consoles.

![image](https://user-images.githubusercontent.com/4237834/162340514-bc58ab91-023e-4622-8f60-1a8f50d5659c.png)

**Comment by djkido316** [comment]
Thank you good sir, Issue has been resolved, Though i tried several controllers even a xbox 360 wired one all had the same issue on Linux but they are completely even with 0% deadzone.

But thank you nevertheless!
